### PR TITLE
B3 custom commands support

### PR DESCRIPTION
**Pull request by BlackHawk94**

### CODE REVIEW

**Comment by BlackHawk94** [comment]
need to be tested before push

**Comment by doctorluk** [comment]
This will not work and contains far too many commands in the code that this mod is not made for.

Finish the changes before requesting a pull.

**Comment by AlexanderCurl** [comment]
Here is what you need, if you really want to.
https://github.com/leiizko/cod4_scriptcommands
Sorry to post a closed pull request.

**Comment by doctorluk** [comment]
All good, thanks for the link!

**Pull request closed without merging**
